### PR TITLE
Require intl

### PR DESCRIPTION
**Pull request by scotchapman**
Problem:
I was getting this error 'IntlPolyfill is not defined' on unsupported locale

Solution:
Require intl when isIntlLocaleSupported is false to provide the IntlPolyfill. 
require("intl/locale-data/jsonp/' + locale + '") returns eval("IntlPolyfill.__addLocaleData())

### CODE REVIEW

**Comment by danilobuerger** [comment]
Thank you for your PR @scotchapman. I do not intend to include the whole intl polyfill in each locale chunk as that would massively increase their size. You should load the intl polyfill before hand. This should probably be mentioned in the README.

**Comment by scotchapman** [comment]
Ok. Thanks for the clarification.  So would you recommend using a function similar to `loadIntlPolyfill` in the [isomorphic500 util](https://github.com/gpbl/isomorphic500/blob/a310365a1d4f4fc53e2c9cf11e050bc59ef935b4/src/utils/IntlUtils.js#L13) to check if the intl polyfill is needed for the locale?

**Comment by danilobuerger** [comment]
Yes

**Comment by lochstar** [comment]
@scotchapman I went with the suggestion here: https://github.com/andyearnshaw/Intl.js#intljs-and-browserifywebpack

e.g.

``` javascript
if (!global.Intl) {
  require.ensure([
    'intl',
  ], function (require) {
    require('intl');
    runApp();
  });
} else {
  runApp();
}
```

**Pull request closed without merging**
